apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumeClaimName }}
  labels:
    type: {{ .Values.volumeClaimtype }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - {{ .Values.accessMode }}
  hostPath:
    path: {{ .Values.hostPath | quote }}
