apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.appName }}
  clusterIP: {{ .Values.clusterIP }}